const primitives=[
    {
        "name": "duplicate",
        "description": "Duplicate the top value on the stack",
        "glyph": ".",
        "count_inputs": 1,
        "count_outputs": 2,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "over",
        "description": "Duplicate the second-to-top value to the top of the stack",
        "glyph": ",",
        "count_inputs": 2,
        "count_outputs": 3,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "flip",
        "description": "Swap the top two values on the stack",
        "glyph": ":",
        "count_inputs": 2,
        "count_outputs": 2,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "pop",
        "description": "Discard the top stack value",
        "glyph": "◌",
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "identity",
        "description": "Do nothing with one value",
        "glyph": "∘",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "not",
        "description": "Logical not",
        "glyph": "¬",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "sign",
        "description": "Numerical sign (1, ¯1, or 0)",
        "glyph": "±",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "negate",
        "description": "Negate a number",
        "glyph": "¯",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "absolute value",
        "description": "Get the absolute value of a number",
        "glyph": "⌵",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "sqrt",
        "description": "Take the square root of a number",
        "glyph": "√",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "sine",
        "description": "Get the sine of a number",
        "glyph": "○",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "floor",
        "description": "Round to the nearest integer towards ¯∞",
        "glyph": "⌊",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "ceiling",
        "description": "Round to the nearest integer towards ∞",
        "glyph": "⌈",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "round",
        "description": "Round to the nearest integer",
        "glyph": "⁅",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "equals",
        "description": "Compare for equality",
        "glyph": "=",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "not equals",
        "description": "Compare for inequality",
        "glyph": "≠",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "less than",
        "description": "Compare for less than",
        "glyph": "<",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "less or equal",
        "description": "Compare for less than or equal",
        "glyph": "≤",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "greater than",
        "description": "Compare for greater than",
        "glyph": ">",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "greater or equal",
        "description": "Compare for greater than or equal",
        "glyph": "≥",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "add",
        "description": "Add values",
        "glyph": "+",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "subtract",
        "description": "Subtract values",
        "glyph": "-",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "multiply",
        "description": "Multiply values",
        "glyph": "×",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "divide",
        "description": "Divide values",
        "glyph": "÷",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "modulus",
        "description": "Modulo values",
        "glyph": "◿",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "power",
        "description": "Raise a value to a power",
        "glyph": "ⁿ",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "logarithm",
        "description": "Get the based logarithm of a number",
        "glyph": "ₙ",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "minimum",
        "description": "Take the minimum of two arrays",
        "glyph": "↧",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "maximum",
        "description": "Take the maximum of two arrays",
        "glyph": "↥",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "atangent",
        "description": "Take the arctangent of two numbers",
        "glyph": "∠",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "complex",
        "description": "Make a complex number",
        "glyph": "ℂ",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicPervasive",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "length",
        "description": "Get the number of rows in an array",
        "glyph": "⧻",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "shape",
        "description": "Get the dimensions of an array",
        "glyph": "△",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "range",
        "description": "Make an array of all natural numbers less than a number",
        "glyph": "⇡",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "first",
        "description": "Get the first row of an array",
        "glyph": "⊢",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "reverse",
        "description": "Reverse the rows of an array",
        "glyph": "⇌",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "deshape",
        "description": "Make an array 1-dimensional",
        "glyph": "♭",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "fix",
        "description": "Add a length-1 axis to an array",
        "glyph": "¤",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "bits",
        "description": "Encode an array as bits (LSB-first)",
        "glyph": "⋯",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "transpose",
        "description": "Rotate the shape of an array",
        "glyph": "⍉",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "rise",
        "description": "Get the indices into an array if it were sorted ascending",
        "glyph": "⍏",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "fall",
        "description": "Get the indices into an array if it were sorted descending",
        "glyph": "⍖",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "where",
        "description": "Get indices where array values are not equal to zero",
        "glyph": "⊚",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "classify",
        "description": "Assign a unique index to each unique element in an array",
        "glyph": "⊛",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "deduplicate",
        "description": "Remove duplicate elements from an array",
        "glyph": "◴",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "unique",
        "description": "Get a mask of first occurrences of items in an array",
        "glyph": "◰",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "box",
        "description": "Turn an array into a box",
        "glyph": "□",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "MonadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "parse",
        "description": "Parse a string as a number",
        "glyph": "⋕",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "match",
        "description": "Check if two arrays are exactly the same",
        "glyph": "≍",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "couple",
        "description": "Combine two arrays as rows of a new array",
        "glyph": "⊟",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "join",
        "description": "Append two arrays end-to-end",
        "glyph": "⊂",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "select",
        "description": "Select multiple rows from an array",
        "glyph": "⊏",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "pick",
        "description": "Index a row or elements from an array",
        "glyph": "⊡",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "reshape",
        "description": "Change the shape of an array",
        "glyph": "↯",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "rerank",
        "description": "Change the rank of an array's rows",
        "glyph": "☇",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "take",
        "description": "Take the first n elements of an array",
        "glyph": "↙",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "drop",
        "description": "Drop the first n elements of an array",
        "glyph": "↘",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "rotate",
        "description": "Rotate the elements of an array by n",
        "glyph": "↻",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "windows",
        "description": "The n-wise windows of an array",
        "glyph": "◫",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "keep",
        "description": "Discard or copy some rows of an array",
        "glyph": "▽",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "find",
        "description": "Find the occurences of one array in another",
        "glyph": "⌕",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "member",
        "description": "Check if each row of one array exists in another",
        "glyph": "∊",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "indexof",
        "description": "Find the first index of each row of one array in another",
        "glyph": "⊗",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "DyadicArray",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "reduce",
        "description": "Apply a reducing function to an array",
        "glyph": "/",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "AggregatingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "fold",
        "description": "Apply a function to aggregate arrays",
        "glyph": "∧",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "AggregatingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "scan",
        "description": "Reduce, but keep intermediate values",
        "glyph": "\\",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "AggregatingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "each",
        "description": "Apply a function to each element of an array or arrays.",
        "glyph": "∵",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "rows",
        "description": "Apply a function to each row of an array or arrays",
        "glyph": "≡",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "table",
        "description": "Apply a function to each combination of rows of two arrays",
        "glyph": "⊞",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "cross",
        "description": "Apply a function to each combination of rows of arrays",
        "glyph": "⊠",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": true
    },
    {
        "name": "repeat",
        "description": "Repeat a function a number of times",
        "glyph": "⍥",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "group",
        "description": "Group elements of an array into buckets by index",
        "glyph": "⊕",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "AggregatingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "partition",
        "description": "Group sequential sections of an array",
        "glyph": "⊜",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "AggregatingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "unpack",
        "description": "Apply a function with implicit unboxing",
        "glyph": "⊐",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": true
    },
    {
        "name": "content",
        "description": "Unbox the arguments to a function before calling it",
        "glyph": "⊔",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "gap",
        "description": "Discard the top stack value then call a function",
        "glyph": "⋅",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "dip",
        "description": "Temporarily pop the top value off the stack and call a function",
        "glyph": "⊙",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "both",
        "description": "Call a function on two sets of values",
        "glyph": "∩",
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "un",
        "description": "Invert the behavior of a function",
        "glyph": "°",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "InversionModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "rectify",
        "description": "Set a function as its own inverse",
        "glyph": "⌅",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "InversionModifier",
        "experimental": true,
        "deprecated": true
    },
    {
        "name": "setinv",
        "description": "Set the un-compatible inverse of a function",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "InversionModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "setund",
        "description": "Set the under-compatible inverse of a function",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 3,
        "primitive_class": "InversionModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "under",
        "description": "Apply a function under another",
        "glyph": "⍜",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "InversionModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "fork",
        "description": "Call two functions on the same values",
        "glyph": "⊃",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "cascade",
        "description": "Call one function after another, reusing some values",
        "glyph": "⪾",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "Planet",
        "experimental": true,
        "deprecated": true
    },
    {
        "name": "bracket",
        "description": "Call two functions on two distinct sets of values",
        "glyph": "⊓",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "Planet",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "all",
        "description": "Call a function on many distinct sets of values",
        "glyph": "⋔",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "Planet",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "do",
        "description": "Repeat a function while a condition holds",
        "glyph": "⍢",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "IteratingModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "fill",
        "description": "Set the fill value for a function",
        "glyph": "⬚",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "try",
        "description": "Call a function and catch errors",
        "glyph": "⍣",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 2,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "assert",
        "description": "Throw an error if a condition is not met",
        "glyph": "⍤",
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "this",
        "description": "Set a function to recur to",
        "glyph": "↬",
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "Misc",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "recur",
        "description": "Call a function recursively",
        "glyph": "↫",
        "count_inputs": 0,
        "count_outputs": null,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "random",
        "description": "Generate a random number in the range [0, 1)",
        "glyph": "⚂",
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "bind",
        "description": "Bind local values",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "memo",
        "description": "Memoize a function",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "comptime",
        "description": "Run a function at compile time",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "spawn",
        "description": "Spawn a thread",
        "glyph": null,
        "count_inputs": null,
        "count_outputs": 1,
        "count_modifier_inputs": 1,
        "primitive_class": "OtherModifier",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "wait",
        "description": "Wait for a thread to finish and push its results to the stack",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "send",
        "description": "Send a value to a thread",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "recv",
        "description": "Receive a value from a thread",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "tryrecv",
        "description": "Try to receive a value from a thread",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "gen",
        "description": "Generate a random number between 0 and 1 from a seed, as well as the next seed",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 2,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "deal",
        "description": "Randomly reorder the rows of an array with a seed",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "regex",
        "description": "Match a regex pattern",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "utf",
        "description": "Convert a string to UTF-8 bytes",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "tag",
        "description": "Generate a unique tag",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "type",
        "description": "Check the type of an array",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "now",
        "description": "Get the current time in seconds",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Misc",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "eta",
        "description": "The number of radians in a quarter circle",
        "glyph": "η",
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Constant",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "pi",
        "description": "The ratio of a circle's circumference to its diameter",
        "glyph": "π",
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Constant",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "tau",
        "description": "The ratio of a circle's circumference to its radius",
        "glyph": "τ",
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Constant",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "infinity",
        "description": "The biggest number",
        "glyph": "∞",
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Constant",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "map",
        "description": "Create a hashmap from lists of keys and values",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Map",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "insert",
        "description": "Insert a key-value pair into a map array",
        "glyph": null,
        "count_inputs": 3,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Map",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "has",
        "description": "Check if a map array has a key",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Map",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "get",
        "description": "Get the value corresponding to a key in a map array",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Map",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "remove",
        "description": "Remove the value corresponding to a key from a map array",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Map",
        "experimental": true,
        "deprecated": false
    },
    {
        "name": "stack",
        "description": "Debug print all stack values without popping them",
        "glyph": "?",
        "count_inputs": 0,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "trace",
        "description": "Debug print the top value on the stack without popping it",
        "glyph": "⸮",
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "dump",
        "description": "Debug print all the values currently on stack without popping them",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 0,
        "count_modifier_inputs": 1,
        "primitive_class": "Stack",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&s",
        "description": "Print a nicely formatted representation of a value to stdout",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(StdIO)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&pf",
        "description": "Print a value to stdout",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(StdIO)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&p",
        "description": "Print a value to stdout followed by a newline",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(StdIO)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&sc",
        "description": "Read a line from stdin",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(StdIO)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ts",
        "description": "Get the size of the terminal",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Env)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&raw",
        "description": "Set the terminal to raw mode",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Env)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&args",
        "description": "Get the command line arguments",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Env)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&var",
        "description": "Get the value of an environment variable",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Env)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&runi",
        "description": "Run a command and wait for it to finish",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Command)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&runc",
        "description": "Run a command and wait for it to finish",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 3,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Command)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&cd",
        "description": "Change the current directory",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&sl",
        "description": "Sleep for n seconds",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Misc)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&rs",
        "description": "Read at most n bytes from a stream",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Stream)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&rb",
        "description": "Read at most n bytes from a stream",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Stream)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ru",
        "description": "Read from a stream until a delimiter is reached",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Stream)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&w",
        "description": "Write an array to a stream",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Stream)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&i",
        "description": "Import an item from a file",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&invk",
        "description": "Invoke a path with the system's default program",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Command)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&cl",
        "description": "Close a stream by its handle",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Stream)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fo",
        "description": "Open a file and return a handle to it",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fc",
        "description": "Create a file and return a handle to it",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fde",
        "description": "Delete a file or directory",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ftr",
        "description": "Move a file or directory to the trash",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fe",
        "description": "Check if a file exists at a path",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fld",
        "description": "List the contents of a directory",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fif",
        "description": "Check if a path is a file",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fras",
        "description": "Read all the contents of a file into a string",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&frab",
        "description": "Read all the contents of a file into a byte array",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&fwa",
        "description": "Write the entire contents of an array to a file",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Filesystem)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&imd",
        "description": "Decode an image from a byte array",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Images)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ime",
        "description": "Encode an image into a byte array with the specified format",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Images)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ims",
        "description": "Show an image",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Images)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&gifd",
        "description": "Decode a gif from a byte array",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 2,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Gifs)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&gife",
        "description": "Encode a gif into a byte array",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Gifs)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&gifs",
        "description": "Show a gif",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Gifs)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ad",
        "description": "Decode audio from a byte array",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Audio)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ae",
        "description": "Encode audio into a byte array",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Audio)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ap",
        "description": "Play some audio",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Audio)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&asr",
        "description": "Get the sample rate of the audio output backend",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Audio)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&ast",
        "description": "Synthesize and stream audio",
        "glyph": null,
        "count_inputs": 0,
        "count_outputs": 0,
        "count_modifier_inputs": 1,
        "primitive_class": "Sys(Audio)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpl",
        "description": "Create a TCP listener and bind it to an address",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpa",
        "description": "Accept a connection with a TCP listener",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpc",
        "description": "Create a TCP socket and connect it to an address",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpsnb",
        "description": "Set a TCP socket to non-blocking mode",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpsrt",
        "description": "Set the read timeout of a TCP socket in seconds",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpswt",
        "description": "Set the write timeout of a TCP socket in seconds",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 0,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&tcpaddr",
        "description": "Get the connection address of a TCP socket",
        "glyph": null,
        "count_inputs": 1,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    },
    {
        "name": "&httpsw",
        "description": "Make an HTTP request",
        "glyph": null,
        "count_inputs": 2,
        "count_outputs": 1,
        "count_modifier_inputs": null,
        "primitive_class": "Sys(Tcp)",
        "experimental": false,
        "deprecated": false
    }
];