[package]
edition = "2021"
name = "tester"
version = "0.1.0"

[dependencies]
uiua = {git="https://github.com/uiua-lang/uiua", branch="main"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"